# Goal: whenever someone change the python code, the linter will check if the file syntax, format, indentation is correct or not.

name: Auto Linter

on: 
  push: 
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone/checklout the code
        uses: actions/checkout@v7
        
