# Goal: whenever someone change the python code, the linter will check if the file syntax, format, indentation is correct or not.

name: Auto Linter

on: 
  push: 
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone/checklout the code
        uses: actions/checkout@v7

      - name: install linter
        run: pip install ruff

      - name: check the file for linting
        run: ruff check .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
        
